# Default values for ecflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod
cloud: aws
prodType: latest

storage:
  persistent: true
  # only applicable when persistent: true
  size: 128Mi
  storageClassName: gp3-csi

server:
  port: 5237
  home: /ecflow
  base: /ecflow/suites
  ssl: true
  egress: true
  suites:
    repos:
    - name: ecflow-smartmet-nwc
      host: github.com/fmidev/ecflow-smartmet-nwc.git
      branch: main
    sshKey:
      name:
    accessToken: 
      user: fmidev
      name: git-read-token
  resources:
    limits:
      cpu: "1"
      memory: 850Mi
    requests:
      cpu: "1"
      memory: 512Mi

logserver:
  enabled: true
  port: 9316
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi
 
api:
  enabled: true
  tokens:
    fileName: "rosa-ecflow-api-token.json"
    configMapName: "ecflow-api-token"
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi
  route:
    enabled: true
    host: snwc-ecflow-dev.apps.rosa.fmi-rosa-dev.ewcf.p3.openshiftapps.com
