{{- if .Values.api.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Values.api.route.host }}
  port:
    targetPort: "8080-tcp"
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-http
    weight: 100
  wildcardPolicy: None
{{- end }}
